# Generated by Django 3.1 on 2020-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display',
            field=models.ImageField(upload_to='profile-display/<django.db.models.fields.CharField>'),
        ),
    ]
