# Generated by Django 3.1.7 on 2021-06-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display',
        ),

        migrations.AddField(
            model_name='profile',
            name='display',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2016/08/31/11/54/user-1633249_1280.png', max_length=255, verbose_name='Display picture url'),
        ),
    ]
