# Generated by Django 3.1 on 2020-08-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200815_1536'),
        ('profiles', '0002_auto_20200815_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed_profiles',
            field=models.ManyToManyField(blank=True, related_name='_profile_followed_profiles_+', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='starred_articles',
            field=models.ManyToManyField(blank=True, related_name='starred', to='articles.Article'),
        ),
    ]
