# Generated by Django 3.1 on 2020-08-27 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200827_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed_profiles',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
