# Generated by Django 3.1 on 2020-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200820_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='article-cover/<django_extensions.db.fields.AutoSlugField>'),
        ),
    ]
