# Generated by Django 3.1.7 on 2021-06-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210226_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover_image',
        ),

        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2019/09/30/14/29/books-4515917_1280.jpg', max_length=255, verbose_name='Cover Image Url'),
        ),
    ]

