# Generated by Django 3.1 on 2020-08-15 22:29

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200815_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('id', 'title'), unique=True, verbose_name='slug'),
        ),
    ]
