# Generated by Django 3.1 on 2020-08-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200827_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
