# Generated by Django 3.1.1 on 2020-09-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_tag_clicked_by_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at']},
        ),
    ]
