# Generated by Django 3.1 on 2020-08-18 12:14

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200818_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=25, populate_from=('name',), verbose_name='slug'),
        ),
    ]
